# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TorrentSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torrent_site1', models.CharField(max_length=128)),
                ('is_use', models.CharField(max_length=128)),
                ('content_table_total_row_cnt', models.CharField(max_length=128)),
                ('content_table_chk_str', models.CharField(max_length=128)),
                ('content_row_cnt_of_date', models.CharField(max_length=128)),
                ('content_row_cnt_of_title', models.CharField(max_length=128)),
                ('max_search_page', models.CharField(max_length=128)),
                ('ent_url', models.CharField(max_length=128)),
                ('drama_url', models.CharField(max_length=128)),
                ('docu_url', models.CharField(max_length=128)),
                ('url_page_prefix', models.CharField(max_length=128)),
                ('url_page_suffix', models.CharField(max_length=128)),
                ('date_format', models.CharField(max_length=128)),
            ],
        ),
    ]
