# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_mgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentsite',
            name='url_page_suffix',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
