# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_mgr', '0004_auto_20171030_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentsite',
            name='date_format2',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='torrentsite',
            name='date_format3',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
