# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_mgr', '0005_auto_20171030_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentsite',
            name='last_get_magnet_date',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
